// source: common/company_tax_exempt_files.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.proto.CompanyTaxExemptFiles', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.CompanyTaxExemptFiles = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.CompanyTaxExemptFiles, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.CompanyTaxExemptFiles.displayName = 'proto.proto.CompanyTaxExemptFiles';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.CompanyTaxExemptFiles.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.CompanyTaxExemptFiles.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.CompanyTaxExemptFiles} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.CompanyTaxExemptFiles.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    companyId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    originalFilename: jspb.Message.getFieldWithDefault(msg, 3, ""),
    internalFilename: jspb.Message.getFieldWithDefault(msg, 4, ""),
    fileSize: jspb.Message.getFieldWithDefault(msg, 5, 0),
    extension: jspb.Message.getFieldWithDefault(msg, 6, ""),
    deleted: jspb.Message.getFieldWithDefault(msg, 7, 0),
    md5Base64: jspb.Message.getFieldWithDefault(msg, 8, ""),
    mimeContentType: jspb.Message.getFieldWithDefault(msg, 9, ""),
    creationTime: jspb.Message.getFieldWithDefault(msg, 10, 0),
    recentlyUsed: jspb.Message.getFieldWithDefault(msg, 11, 0),
    link: jspb.Message.getFieldWithDefault(msg, 12, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.CompanyTaxExemptFiles}
 */
proto.proto.CompanyTaxExemptFiles.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.CompanyTaxExemptFiles;
  return proto.proto.CompanyTaxExemptFiles.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.CompanyTaxExemptFiles} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.CompanyTaxExemptFiles}
 */
proto.proto.CompanyTaxExemptFiles.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCompanyId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginalFilename(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setInternalFilename(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFileSize(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setExtension$(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDeleted(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setMd5Base64(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setMimeContentType(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreationTime(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRecentlyUsed(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setLink(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.CompanyTaxExemptFiles.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.CompanyTaxExemptFiles.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.CompanyTaxExemptFiles} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.CompanyTaxExemptFiles.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getCompanyId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getOriginalFilename();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getInternalFilename();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getFileSize();
  if (f !== 0) {
    writer.writeInt32(
      5,
      f
    );
  }
  f = message.getExtension$();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getDeleted();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getMd5Base64();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getMimeContentType();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getCreationTime();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
  f = message.getRecentlyUsed();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getLink();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.proto.CompanyTaxExemptFiles.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.CompanyTaxExemptFiles} returns this
 */
proto.proto.CompanyTaxExemptFiles.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 company_id = 2;
 * @return {number}
 */
proto.proto.CompanyTaxExemptFiles.prototype.getCompanyId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.CompanyTaxExemptFiles} returns this
 */
proto.proto.CompanyTaxExemptFiles.prototype.setCompanyId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string original_filename = 3;
 * @return {string}
 */
proto.proto.CompanyTaxExemptFiles.prototype.getOriginalFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.CompanyTaxExemptFiles} returns this
 */
proto.proto.CompanyTaxExemptFiles.prototype.setOriginalFilename = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string internal_filename = 4;
 * @return {string}
 */
proto.proto.CompanyTaxExemptFiles.prototype.getInternalFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.CompanyTaxExemptFiles} returns this
 */
proto.proto.CompanyTaxExemptFiles.prototype.setInternalFilename = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional int32 file_size = 5;
 * @return {number}
 */
proto.proto.CompanyTaxExemptFiles.prototype.getFileSize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.CompanyTaxExemptFiles} returns this
 */
proto.proto.CompanyTaxExemptFiles.prototype.setFileSize = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string extension = 6;
 * @return {string}
 */
proto.proto.CompanyTaxExemptFiles.prototype.getExtension$ = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.CompanyTaxExemptFiles} returns this
 */
proto.proto.CompanyTaxExemptFiles.prototype.setExtension$ = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int32 deleted = 7;
 * @return {number}
 */
proto.proto.CompanyTaxExemptFiles.prototype.getDeleted = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.CompanyTaxExemptFiles} returns this
 */
proto.proto.CompanyTaxExemptFiles.prototype.setDeleted = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional string md5_base_64 = 8;
 * @return {string}
 */
proto.proto.CompanyTaxExemptFiles.prototype.getMd5Base64 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.CompanyTaxExemptFiles} returns this
 */
proto.proto.CompanyTaxExemptFiles.prototype.setMd5Base64 = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string mime_content_type = 9;
 * @return {string}
 */
proto.proto.CompanyTaxExemptFiles.prototype.getMimeContentType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.CompanyTaxExemptFiles} returns this
 */
proto.proto.CompanyTaxExemptFiles.prototype.setMimeContentType = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional int64 creation_time = 10;
 * @return {number}
 */
proto.proto.CompanyTaxExemptFiles.prototype.getCreationTime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.CompanyTaxExemptFiles} returns this
 */
proto.proto.CompanyTaxExemptFiles.prototype.setCreationTime = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 recently_used = 11;
 * @return {number}
 */
proto.proto.CompanyTaxExemptFiles.prototype.getRecentlyUsed = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.CompanyTaxExemptFiles} returns this
 */
proto.proto.CompanyTaxExemptFiles.prototype.setRecentlyUsed = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional string link = 12;
 * @return {string}
 */
proto.proto.CompanyTaxExemptFiles.prototype.getLink = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.CompanyTaxExemptFiles} returns this
 */
proto.proto.CompanyTaxExemptFiles.prototype.setLink = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


goog.object.extend(exports, proto.proto);
