// source: common/sp_order_sku_replace.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.proto.SpOrderSkuReplace', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.SpOrderSkuReplace = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.SpOrderSkuReplace, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.SpOrderSkuReplace.displayName = 'proto.proto.SpOrderSkuReplace';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.SpOrderSkuReplace.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.SpOrderSkuReplace.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.SpOrderSkuReplace} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.SpOrderSkuReplace.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    spOrderSkuId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    status: jspb.Message.getFieldWithDefault(msg, 3, ""),
    reasonId: jspb.Message.getFieldWithDefault(msg, 4, 0),
    creationTime: jspb.Message.getFieldWithDefault(msg, 5, ""),
    requestTime: jspb.Message.getFieldWithDefault(msg, 6, ""),
    requestPersonId: jspb.Message.getFieldWithDefault(msg, 7, 0),
    requestPersonType: jspb.Message.getFieldWithDefault(msg, 8, ""),
    approveTime: jspb.Message.getFieldWithDefault(msg, 9, ""),
    approvePersonId: jspb.Message.getFieldWithDefault(msg, 10, 0),
    approvePersonType: jspb.Message.getFieldWithDefault(msg, 11, ""),
    declineTime: jspb.Message.getFieldWithDefault(msg, 12, ""),
    declinePersonId: jspb.Message.getFieldWithDefault(msg, 13, 0),
    declinePersonType: jspb.Message.getFieldWithDefault(msg, 14, ""),
    deleted: jspb.Message.getFieldWithDefault(msg, 15, 0),
    quantity: jspb.Message.getFieldWithDefault(msg, 16, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.SpOrderSkuReplace}
 */
proto.proto.SpOrderSkuReplace.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.SpOrderSkuReplace;
  return proto.proto.SpOrderSkuReplace.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.SpOrderSkuReplace} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.SpOrderSkuReplace}
 */
proto.proto.SpOrderSkuReplace.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSpOrderSkuId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setReasonId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setCreationTime(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestTime(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRequestPersonId(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequestPersonType(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setApproveTime(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setApprovePersonId(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setApprovePersonType(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeclineTime(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDeclinePersonId(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeclinePersonType(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDeleted(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setQuantity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.SpOrderSkuReplace.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.SpOrderSkuReplace.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.SpOrderSkuReplace} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.SpOrderSkuReplace.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getSpOrderSkuId();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getReasonId();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getCreationTime();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getRequestTime();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getRequestPersonId();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getRequestPersonType();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getApproveTime();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getApprovePersonId();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getApprovePersonType();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getDeclineTime();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getDeclinePersonId();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getDeclinePersonType();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getDeleted();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
  f = message.getQuantity();
  if (f !== 0) {
    writer.writeInt32(
      16,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.proto.SpOrderSkuReplace.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 sp_order_sku_id = 2;
 * @return {number}
 */
proto.proto.SpOrderSkuReplace.prototype.getSpOrderSkuId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setSpOrderSkuId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string status = 3;
 * @return {string}
 */
proto.proto.SpOrderSkuReplace.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional int32 reason_id = 4;
 * @return {number}
 */
proto.proto.SpOrderSkuReplace.prototype.getReasonId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setReasonId = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string creation_time = 5;
 * @return {string}
 */
proto.proto.SpOrderSkuReplace.prototype.getCreationTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setCreationTime = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string request_time = 6;
 * @return {string}
 */
proto.proto.SpOrderSkuReplace.prototype.getRequestTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setRequestTime = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int32 request_person_id = 7;
 * @return {number}
 */
proto.proto.SpOrderSkuReplace.prototype.getRequestPersonId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setRequestPersonId = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional string request_person_type = 8;
 * @return {string}
 */
proto.proto.SpOrderSkuReplace.prototype.getRequestPersonType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setRequestPersonType = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string approve_time = 9;
 * @return {string}
 */
proto.proto.SpOrderSkuReplace.prototype.getApproveTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setApproveTime = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional int32 approve_person_id = 10;
 * @return {number}
 */
proto.proto.SpOrderSkuReplace.prototype.getApprovePersonId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setApprovePersonId = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional string approve_person_type = 11;
 * @return {string}
 */
proto.proto.SpOrderSkuReplace.prototype.getApprovePersonType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setApprovePersonType = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string decline_time = 12;
 * @return {string}
 */
proto.proto.SpOrderSkuReplace.prototype.getDeclineTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setDeclineTime = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional int32 decline_person_id = 13;
 * @return {number}
 */
proto.proto.SpOrderSkuReplace.prototype.getDeclinePersonId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setDeclinePersonId = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional string decline_person_type = 14;
 * @return {string}
 */
proto.proto.SpOrderSkuReplace.prototype.getDeclinePersonType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setDeclinePersonType = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional int32 deleted = 15;
 * @return {number}
 */
proto.proto.SpOrderSkuReplace.prototype.getDeleted = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setDeleted = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


/**
 * optional int32 quantity = 16;
 * @return {number}
 */
proto.proto.SpOrderSkuReplace.prototype.getQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.SpOrderSkuReplace} returns this
 */
proto.proto.SpOrderSkuReplace.prototype.setQuantity = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


goog.object.extend(exports, proto.proto);
