// source: shop/orders/buyer/orders/thanksOrderRes.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var common_sp_order_pb = require('../../../../common/sp_order_pb.js');
goog.object.extend(proto, common_sp_order_pb);
var common_sp_order_delivery_information_pb = require('../../../../common/sp_order_delivery_information_pb.js');
goog.object.extend(proto, common_sp_order_delivery_information_pb);
var common_company_location_content_pb = require('../../../../common/company_location_content_pb.js');
goog.object.extend(proto, common_company_location_content_pb);
var common_company_contact_content_pb = require('../../../../common/company_contact_content_pb.js');
goog.object.extend(proto, common_company_contact_content_pb);
var common_sp_order_sku_pb = require('../../../../common/sp_order_sku_pb.js');
goog.object.extend(proto, common_sp_order_sku_pb);
var common_sp_sku_pb = require('../../../../common/sp_sku_pb.js');
goog.object.extend(proto, common_sp_sku_pb);
var common_sp_spu_pb = require('../../../../common/sp_spu_pb.js');
goog.object.extend(proto, common_sp_spu_pb);
var common_sp_sku_images_pb = require('../../../../common/sp_sku_images_pb.js');
goog.object.extend(proto, common_sp_sku_images_pb);
goog.exportSymbol('proto.proto.shop.orders.buyer.thanksOrderRes.Msg', null, global);
goog.exportSymbol('proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation', null, global);
goog.exportSymbol('proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend', null, global);
goog.exportSymbol('proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.displayName = 'proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.displayName = 'proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.repeatedFields_, null);
};
goog.inherits(proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.displayName = 'proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.shop.orders.buyer.thanksOrderRes.Msg.repeatedFields_, null);
};
goog.inherits(proto.proto.shop.orders.buyer.thanksOrderRes.Msg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.orders.buyer.thanksOrderRes.Msg.displayName = 'proto.proto.shop.orders.buyer.thanksOrderRes.Msg';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.toObject = function(includeInstance, msg) {
  var f, obj = {
    spOrderDeliveryInformation: (f = msg.getSpOrderDeliveryInformation()) && common_sp_order_delivery_information_pb.SpOrderDeliveryInformation.toObject(includeInstance, f),
    companyLocationContent: (f = msg.getCompanyLocationContent()) && common_company_location_content_pb.CompanyLocationContent.toObject(includeInstance, f),
    companyContactContent: (f = msg.getCompanyContactContent()) && common_company_contact_content_pb.CompanyContactContent.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation;
  return proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_sp_order_delivery_information_pb.SpOrderDeliveryInformation;
      reader.readMessage(value,common_sp_order_delivery_information_pb.SpOrderDeliveryInformation.deserializeBinaryFromReader);
      msg.setSpOrderDeliveryInformation(value);
      break;
    case 2:
      var value = new common_company_location_content_pb.CompanyLocationContent;
      reader.readMessage(value,common_company_location_content_pb.CompanyLocationContent.deserializeBinaryFromReader);
      msg.setCompanyLocationContent(value);
      break;
    case 3:
      var value = new common_company_contact_content_pb.CompanyContactContent;
      reader.readMessage(value,common_company_contact_content_pb.CompanyContactContent.deserializeBinaryFromReader);
      msg.setCompanyContactContent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpOrderDeliveryInformation();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_sp_order_delivery_information_pb.SpOrderDeliveryInformation.serializeBinaryToWriter
    );
  }
  f = message.getCompanyLocationContent();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      common_company_location_content_pb.CompanyLocationContent.serializeBinaryToWriter
    );
  }
  f = message.getCompanyContactContent();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      common_company_contact_content_pb.CompanyContactContent.serializeBinaryToWriter
    );
  }
};


/**
 * optional proto.SpOrderDeliveryInformation sp_order_delivery_information = 1;
 * @return {?proto.proto.SpOrderDeliveryInformation}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.prototype.getSpOrderDeliveryInformation = function() {
  return /** @type{?proto.proto.SpOrderDeliveryInformation} */ (
    jspb.Message.getWrapperField(this, common_sp_order_delivery_information_pb.SpOrderDeliveryInformation, 1));
};


/**
 * @param {?proto.proto.SpOrderDeliveryInformation|undefined} value
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation} returns this
*/
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.prototype.setSpOrderDeliveryInformation = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation} returns this
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.prototype.clearSpOrderDeliveryInformation = function() {
  return this.setSpOrderDeliveryInformation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.prototype.hasSpOrderDeliveryInformation = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional proto.CompanyLocationContent company_location_content = 2;
 * @return {?proto.proto.CompanyLocationContent}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.prototype.getCompanyLocationContent = function() {
  return /** @type{?proto.proto.CompanyLocationContent} */ (
    jspb.Message.getWrapperField(this, common_company_location_content_pb.CompanyLocationContent, 2));
};


/**
 * @param {?proto.proto.CompanyLocationContent|undefined} value
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation} returns this
*/
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.prototype.setCompanyLocationContent = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation} returns this
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.prototype.clearCompanyLocationContent = function() {
  return this.setCompanyLocationContent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.prototype.hasCompanyLocationContent = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional proto.CompanyContactContent company_contact_content = 3;
 * @return {?proto.proto.CompanyContactContent}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.prototype.getCompanyContactContent = function() {
  return /** @type{?proto.proto.CompanyContactContent} */ (
    jspb.Message.getWrapperField(this, common_company_contact_content_pb.CompanyContactContent, 3));
};


/**
 * @param {?proto.proto.CompanyContactContent|undefined} value
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation} returns this
*/
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.prototype.setCompanyContactContent = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation} returns this
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.prototype.clearCompanyContactContent = function() {
  return this.setCompanyContactContent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.prototype.hasCompanyContactContent = function() {
  return jspb.Message.getField(this, 3) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    key: jspb.Message.getFieldWithDefault(msg, 2, ""),
    value: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption;
  return proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setKey(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setValue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getKey();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getValue();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption} returns this
 */
proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string key = 2;
 * @return {string}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.prototype.getKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption} returns this
 */
proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.prototype.setKey = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string value = 3;
 * @return {string}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.prototype.getValue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption} returns this
 */
proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.prototype.setValue = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.toObject = function(includeInstance, msg) {
  var f, obj = {
    spOrderSku: (f = msg.getSpOrderSku()) && common_sp_order_sku_pb.SpOrderSku.toObject(includeInstance, f),
    spSku: (f = msg.getSpSku()) && common_sp_sku_pb.SpSku.toObject(includeInstance, f),
    spSpu: (f = msg.getSpSpu()) && common_sp_spu_pb.SpSpu.toObject(includeInstance, f),
    skuOptionList: jspb.Message.toObjectList(msg.getSkuOptionList(),
    proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.toObject, includeInstance),
    spSkuImage: (f = msg.getSpSkuImage()) && common_sp_sku_images_pb.SpSkuImages.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend;
  return proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_sp_order_sku_pb.SpOrderSku;
      reader.readMessage(value,common_sp_order_sku_pb.SpOrderSku.deserializeBinaryFromReader);
      msg.setSpOrderSku(value);
      break;
    case 2:
      var value = new common_sp_sku_pb.SpSku;
      reader.readMessage(value,common_sp_sku_pb.SpSku.deserializeBinaryFromReader);
      msg.setSpSku(value);
      break;
    case 3:
      var value = new common_sp_spu_pb.SpSpu;
      reader.readMessage(value,common_sp_spu_pb.SpSpu.deserializeBinaryFromReader);
      msg.setSpSpu(value);
      break;
    case 4:
      var value = new proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption;
      reader.readMessage(value,proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.deserializeBinaryFromReader);
      msg.addSkuOption(value);
      break;
    case 5:
      var value = new common_sp_sku_images_pb.SpSkuImages;
      reader.readMessage(value,common_sp_sku_images_pb.SpSkuImages.deserializeBinaryFromReader);
      msg.setSpSkuImage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpOrderSku();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_sp_order_sku_pb.SpOrderSku.serializeBinaryToWriter
    );
  }
  f = message.getSpSku();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      common_sp_sku_pb.SpSku.serializeBinaryToWriter
    );
  }
  f = message.getSpSpu();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      common_sp_spu_pb.SpSpu.serializeBinaryToWriter
    );
  }
  f = message.getSkuOptionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption.serializeBinaryToWriter
    );
  }
  f = message.getSpSkuImage();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      common_sp_sku_images_pb.SpSkuImages.serializeBinaryToWriter
    );
  }
};


/**
 * optional proto.SpOrderSku sp_order_sku = 1;
 * @return {?proto.proto.SpOrderSku}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.getSpOrderSku = function() {
  return /** @type{?proto.proto.SpOrderSku} */ (
    jspb.Message.getWrapperField(this, common_sp_order_sku_pb.SpOrderSku, 1));
};


/**
 * @param {?proto.proto.SpOrderSku|undefined} value
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend} returns this
*/
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.setSpOrderSku = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend} returns this
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.clearSpOrderSku = function() {
  return this.setSpOrderSku(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.hasSpOrderSku = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional proto.SpSku sp_sku = 2;
 * @return {?proto.proto.SpSku}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.getSpSku = function() {
  return /** @type{?proto.proto.SpSku} */ (
    jspb.Message.getWrapperField(this, common_sp_sku_pb.SpSku, 2));
};


/**
 * @param {?proto.proto.SpSku|undefined} value
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend} returns this
*/
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.setSpSku = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend} returns this
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.clearSpSku = function() {
  return this.setSpSku(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.hasSpSku = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional proto.SpSpu sp_spu = 3;
 * @return {?proto.proto.SpSpu}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.getSpSpu = function() {
  return /** @type{?proto.proto.SpSpu} */ (
    jspb.Message.getWrapperField(this, common_sp_spu_pb.SpSpu, 3));
};


/**
 * @param {?proto.proto.SpSpu|undefined} value
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend} returns this
*/
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.setSpSpu = function(value) {
  return jspb.Message.setWrapperField(this, 3, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend} returns this
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.clearSpSpu = function() {
  return this.setSpSpu(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.hasSpSpu = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * repeated SkuOption sku_option = 4;
 * @return {!Array<!proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption>}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.getSkuOptionList = function() {
  return /** @type{!Array<!proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption, 4));
};


/**
 * @param {!Array<!proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption>} value
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend} returns this
*/
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.setSkuOptionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.addSkuOption = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.proto.shop.orders.buyer.thanksOrderRes.SkuOption, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend} returns this
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.clearSkuOptionList = function() {
  return this.setSkuOptionList([]);
};


/**
 * optional proto.SpSkuImages sp_sku_image = 5;
 * @return {?proto.proto.SpSkuImages}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.getSpSkuImage = function() {
  return /** @type{?proto.proto.SpSkuImages} */ (
    jspb.Message.getWrapperField(this, common_sp_sku_images_pb.SpSkuImages, 5));
};


/**
 * @param {?proto.proto.SpSkuImages|undefined} value
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend} returns this
*/
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.setSpSkuImage = function(value) {
  return jspb.Message.setWrapperField(this, 5, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend} returns this
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.clearSpSkuImage = function() {
  return this.setSpSkuImage(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.prototype.hasSpSkuImage = function() {
  return jspb.Message.getField(this, 5) != null;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.orders.buyer.thanksOrderRes.Msg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.orders.buyer.thanksOrderRes.Msg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.toObject = function(includeInstance, msg) {
  var f, obj = {
    spOrder: (f = msg.getSpOrder()) && common_sp_order_pb.SpOrder.toObject(includeInstance, f),
    orderDeliveryInformation: (f = msg.getOrderDeliveryInformation()) && proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.toObject(includeInstance, f),
    orderedSkuList: jspb.Message.toObjectList(msg.getOrderedSkuList(),
    proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.toObject, includeInstance),
    placedPersonEmail: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.Msg}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.orders.buyer.thanksOrderRes.Msg;
  return proto.proto.shop.orders.buyer.thanksOrderRes.Msg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.orders.buyer.thanksOrderRes.Msg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.Msg}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_sp_order_pb.SpOrder;
      reader.readMessage(value,common_sp_order_pb.SpOrder.deserializeBinaryFromReader);
      msg.setSpOrder(value);
      break;
    case 2:
      var value = new proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation;
      reader.readMessage(value,proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.deserializeBinaryFromReader);
      msg.setOrderDeliveryInformation(value);
      break;
    case 3:
      var value = new proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend;
      reader.readMessage(value,proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.deserializeBinaryFromReader);
      msg.addOrderedSku(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setPlacedPersonEmail(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.orders.buyer.thanksOrderRes.Msg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.orders.buyer.thanksOrderRes.Msg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpOrder();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_sp_order_pb.SpOrder.serializeBinaryToWriter
    );
  }
  f = message.getOrderDeliveryInformation();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation.serializeBinaryToWriter
    );
  }
  f = message.getOrderedSkuList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend.serializeBinaryToWriter
    );
  }
  f = message.getPlacedPersonEmail();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional proto.SpOrder sp_order = 1;
 * @return {?proto.proto.SpOrder}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.getSpOrder = function() {
  return /** @type{?proto.proto.SpOrder} */ (
    jspb.Message.getWrapperField(this, common_sp_order_pb.SpOrder, 1));
};


/**
 * @param {?proto.proto.SpOrder|undefined} value
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.Msg} returns this
*/
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.setSpOrder = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.Msg} returns this
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.clearSpOrder = function() {
  return this.setSpOrder(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.hasSpOrder = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional OrderDeliveryInformation order_delivery_information = 2;
 * @return {?proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.getOrderDeliveryInformation = function() {
  return /** @type{?proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation} */ (
    jspb.Message.getWrapperField(this, proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation, 2));
};


/**
 * @param {?proto.proto.shop.orders.buyer.thanksOrderRes.OrderDeliveryInformation|undefined} value
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.Msg} returns this
*/
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.setOrderDeliveryInformation = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.Msg} returns this
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.clearOrderDeliveryInformation = function() {
  return this.setOrderDeliveryInformation(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.hasOrderDeliveryInformation = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated OrderedSkuExtend ordered_sku = 3;
 * @return {!Array<!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend>}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.getOrderedSkuList = function() {
  return /** @type{!Array<!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend, 3));
};


/**
 * @param {!Array<!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend>} value
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.Msg} returns this
*/
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.setOrderedSkuList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.addOrderedSku = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.proto.shop.orders.buyer.thanksOrderRes.OrderedSkuExtend, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.Msg} returns this
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.clearOrderedSkuList = function() {
  return this.setOrderedSkuList([]);
};


/**
 * optional string placed_person_email = 4;
 * @return {string}
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.getPlacedPersonEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.orders.buyer.thanksOrderRes.Msg} returns this
 */
proto.proto.shop.orders.buyer.thanksOrderRes.Msg.prototype.setPlacedPersonEmail = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


goog.object.extend(exports, proto.proto.shop.orders.buyer.thanksOrderRes);
