// source: shop/buyAgainNew/buyAgainCategoryResponse.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.proto.shop.buyAgainNew.BuyAgainCategory', null, global);
goog.exportSymbol('proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.repeatedFields_, null);
};
goog.inherits(proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.displayName = 'proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.buyAgainNew.BuyAgainCategory = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.shop.buyAgainNew.BuyAgainCategory, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.buyAgainNew.BuyAgainCategory.displayName = 'proto.proto.shop.buyAgainNew.BuyAgainCategory';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    categoriesList: jspb.Message.toObjectList(msg.getCategoriesList(),
    proto.proto.shop.buyAgainNew.BuyAgainCategory.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse}
 */
proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse;
  return proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse}
 */
proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.proto.shop.buyAgainNew.BuyAgainCategory;
      reader.readMessage(value,proto.proto.shop.buyAgainNew.BuyAgainCategory.deserializeBinaryFromReader);
      msg.addCategories(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCategoriesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.proto.shop.buyAgainNew.BuyAgainCategory.serializeBinaryToWriter
    );
  }
};


/**
 * repeated BuyAgainCategory categories = 1;
 * @return {!Array<!proto.proto.shop.buyAgainNew.BuyAgainCategory>}
 */
proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.prototype.getCategoriesList = function() {
  return /** @type{!Array<!proto.proto.shop.buyAgainNew.BuyAgainCategory>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.shop.buyAgainNew.BuyAgainCategory, 1));
};


/**
 * @param {!Array<!proto.proto.shop.buyAgainNew.BuyAgainCategory>} value
 * @return {!proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse} returns this
*/
proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.prototype.setCategoriesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.proto.shop.buyAgainNew.BuyAgainCategory=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.shop.buyAgainNew.BuyAgainCategory}
 */
proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.prototype.addCategories = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.proto.shop.buyAgainNew.BuyAgainCategory, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse} returns this
 */
proto.proto.shop.buyAgainNew.BuyAgainCategoryResponse.prototype.clearCategoriesList = function() {
  return this.setCategoriesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.buyAgainNew.BuyAgainCategory.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.buyAgainNew.BuyAgainCategory.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.buyAgainNew.BuyAgainCategory} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.buyAgainNew.BuyAgainCategory.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    categorytext: jspb.Message.getFieldWithDefault(msg, 2, ""),
    cnt: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.buyAgainNew.BuyAgainCategory}
 */
proto.proto.shop.buyAgainNew.BuyAgainCategory.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.buyAgainNew.BuyAgainCategory;
  return proto.proto.shop.buyAgainNew.BuyAgainCategory.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.buyAgainNew.BuyAgainCategory} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.buyAgainNew.BuyAgainCategory}
 */
proto.proto.shop.buyAgainNew.BuyAgainCategory.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCategorytext(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCnt(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.buyAgainNew.BuyAgainCategory.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.buyAgainNew.BuyAgainCategory.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.buyAgainNew.BuyAgainCategory} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.buyAgainNew.BuyAgainCategory.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getCategorytext();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCnt();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.proto.shop.buyAgainNew.BuyAgainCategory.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.buyAgainNew.BuyAgainCategory} returns this
 */
proto.proto.shop.buyAgainNew.BuyAgainCategory.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string categoryText = 2;
 * @return {string}
 */
proto.proto.shop.buyAgainNew.BuyAgainCategory.prototype.getCategorytext = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.buyAgainNew.BuyAgainCategory} returns this
 */
proto.proto.shop.buyAgainNew.BuyAgainCategory.prototype.setCategorytext = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 cnt = 3;
 * @return {number}
 */
proto.proto.shop.buyAgainNew.BuyAgainCategory.prototype.getCnt = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.buyAgainNew.BuyAgainCategory} returns this
 */
proto.proto.shop.buyAgainNew.BuyAgainCategory.prototype.setCnt = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


goog.object.extend(exports, proto.proto.shop.buyAgainNew);
