// source: shop/buyAgainNew/pullInfiBuyAgainNewRes.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes', null, global);
goog.exportSymbol('proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.displayName = 'proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.repeatedFields_, null);
};
goog.inherits(proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.displayName = 'proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.toObject = function(includeInstance, msg) {
  var f, obj = {
    spuId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    imageLink: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    minPrice: jspb.Message.getFieldWithDefault(msg, 4, ""),
    maxPrice: jspb.Message.getFieldWithDefault(msg, 5, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu}
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu;
  return proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu}
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSpuId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageLink(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMinPrice(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMaxPrice(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpuId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getImageLink();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMinPrice();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMaxPrice();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * optional int32 spu_id = 1;
 * @return {number}
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.prototype.getSpuId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu} returns this
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.prototype.setSpuId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string image_link = 2;
 * @return {string}
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.prototype.getImageLink = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu} returns this
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.prototype.setImageLink = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu} returns this
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string min_price = 4;
 * @return {string}
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.prototype.getMinPrice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu} returns this
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.prototype.setMinPrice = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string max_price = 5;
 * @return {string}
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.prototype.getMaxPrice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu} returns this
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.prototype.setMaxPrice = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    spuList: jspb.Message.toObjectList(msg.getSpuList(),
    proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes}
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes;
  return proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes}
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu;
      reader.readMessage(value,proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.deserializeBinaryFromReader);
      msg.addSpu(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpuList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Spu spu = 1;
 * @return {!Array<!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu>}
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.prototype.getSpuList = function() {
  return /** @type{!Array<!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu, 1));
};


/**
 * @param {!Array<!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu>} value
 * @return {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes} returns this
*/
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.prototype.setSpuList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu}
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.prototype.addSpu = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.Spu, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes} returns this
 */
proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes.BuyAgainNewRes.prototype.clearSpuList = function() {
  return this.setSpuList([]);
};


goog.object.extend(exports, proto.proto.shop.buyAgainNew.pullInfiBuyAgainNewRes);
