// source: shop/product/buyer/pullSpuQuickShopRes.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var common_sp_spu_pb = require('../../../common/sp_spu_pb.js');
goog.object.extend(proto, common_sp_spu_pb);
var common_sp_spu_content_pb = require('../../../common/sp_spu_content_pb.js');
goog.object.extend(proto, common_sp_spu_content_pb);
var common_sp_spu_categories_pb = require('../../../common/sp_spu_categories_pb.js');
goog.object.extend(proto, common_sp_spu_categories_pb);
var common_sp_sku_pb = require('../../../common/sp_sku_pb.js');
goog.object.extend(proto, common_sp_sku_pb);
var common_sp_sku_images_pb = require('../../../common/sp_sku_images_pb.js');
goog.object.extend(proto, common_sp_sku_images_pb);
var common_specifications_pb = require('../../../common/specifications_pb.js');
goog.object.extend(proto, common_specifications_pb);
var common_additional_requirements_pb = require('../../../common/additional_requirements_pb.js');
goog.object.extend(proto, common_additional_requirements_pb);
var common_sp_sku_price_pb = require('../../../common/sp_sku_price_pb.js');
goog.object.extend(proto, common_sp_sku_price_pb);
var common_sp_sku_promotion_price_pb = require('../../../common/sp_sku_promotion_price_pb.js');
goog.object.extend(proto, common_sp_sku_promotion_price_pb);
var common_sp_protocol_sku_price_pb = require('../../../common/sp_protocol_sku_price_pb.js');
goog.object.extend(proto, common_sp_protocol_sku_price_pb);
goog.exportSymbol('proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg', null, global);
goog.exportSymbol('proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option', null, global);
goog.exportSymbol('proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem', null, global);
goog.exportSymbol('proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption', null, global);
goog.exportSymbol('proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem', null, global);
goog.exportSymbol('proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp', null, global);
goog.exportSymbol('proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.displayName = 'proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.repeatedFields_, null);
};
goog.inherits(proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.displayName = 'proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.displayName = 'proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.repeatedFields_, null);
};
goog.inherits(proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.displayName = 'proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.repeatedFields_, null);
};
goog.inherits(proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.displayName = 'proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.repeatedFields_, null);
};
goog.inherits(proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.displayName = 'proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.repeatedFields_, null);
};
goog.inherits(proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.displayName = 'proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem;
  return proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    optionItemList: jspb.Message.toObjectList(msg.getOptionItemList(),
    proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option;
  return proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = new proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem;
      reader.readMessage(value,proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.deserializeBinaryFromReader);
      msg.addOptionItem(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getOptionItemList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 id = 1;
 * @return {number}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.prototype.getId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.prototype.setId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated OptionItem option_item = 3;
 * @return {!Array<!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem>}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.prototype.getOptionItemList = function() {
  return /** @type{!Array<!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem, 3));
};


/**
 * @param {!Array<!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem>} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.prototype.setOptionItemList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.prototype.addOptionItem = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.OptionItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.prototype.clearOptionItemList = function() {
  return this.setOptionItemList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    optionName: jspb.Message.getFieldWithDefault(msg, 1, ""),
    optionItemName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    optionId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    optionItemId: jspb.Message.getFieldWithDefault(msg, 4, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem;
  return proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOptionName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOptionItemName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOptionId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOptionItemId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getOptionName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOptionItemName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getOptionId();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getOptionItemId();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
};


/**
 * optional string option_name = 1;
 * @return {string}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.prototype.getOptionName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.prototype.setOptionName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string option_item_name = 2;
 * @return {string}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.prototype.getOptionItemName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.prototype.setOptionItemName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 option_id = 3;
 * @return {number}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.prototype.getOptionId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.prototype.setOptionId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 option_item_id = 4;
 * @return {number}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.prototype.getOptionItemId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.prototype.setOptionItemId = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.toObject = function(includeInstance, msg) {
  var f, obj = {
    skuId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    skuOptionItemList: jspb.Message.toObjectList(msg.getSkuOptionItemList(),
    proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption;
  return proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSkuId(value);
      break;
    case 2:
      var value = new proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem;
      reader.readMessage(value,proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.deserializeBinaryFromReader);
      msg.addSkuOptionItem(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSkuId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getSkuOptionItemList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 sku_id = 1;
 * @return {number}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.prototype.getSkuId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.prototype.setSkuId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated SkuOptionItem sku_option_item = 2;
 * @return {!Array<!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem>}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.prototype.getSkuOptionItemList = function() {
  return /** @type{!Array<!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem, 2));
};


/**
 * @param {!Array<!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem>} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.prototype.setSkuOptionItemList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.prototype.addSkuOptionItem = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOptionItem, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.prototype.clearSkuOptionItemList = function() {
  return this.setSkuOptionItemList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.repeatedFields_ = [3,4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.toObject = function(includeInstance, msg) {
  var f, obj = {
    spSpu: (f = msg.getSpSpu()) && common_sp_spu_pb.SpSpu.toObject(includeInstance, f),
    spSpuContent: (f = msg.getSpSpuContent()) && common_sp_spu_content_pb.SpSpuContent.toObject(includeInstance, f),
    categoryList: jspb.Message.toObjectList(msg.getCategoryList(),
    common_sp_spu_categories_pb.SpCategoryWp.toObject, includeInstance),
    optionList: jspb.Message.toObjectList(msg.getOptionList(),
    proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.toObject, includeInstance),
    skuOptionList: jspb.Message.toObjectList(msg.getSkuOptionList(),
    proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp;
  return proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_sp_spu_pb.SpSpu;
      reader.readMessage(value,common_sp_spu_pb.SpSpu.deserializeBinaryFromReader);
      msg.setSpSpu(value);
      break;
    case 2:
      var value = new common_sp_spu_content_pb.SpSpuContent;
      reader.readMessage(value,common_sp_spu_content_pb.SpSpuContent.deserializeBinaryFromReader);
      msg.setSpSpuContent(value);
      break;
    case 3:
      var value = new common_sp_spu_categories_pb.SpCategoryWp;
      reader.readMessage(value,common_sp_spu_categories_pb.SpCategoryWp.deserializeBinaryFromReader);
      msg.addCategory(value);
      break;
    case 4:
      var value = new proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option;
      reader.readMessage(value,proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.deserializeBinaryFromReader);
      msg.addOption(value);
      break;
    case 5:
      var value = new proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption;
      reader.readMessage(value,proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.deserializeBinaryFromReader);
      msg.addSkuOption(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpSpu();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_sp_spu_pb.SpSpu.serializeBinaryToWriter
    );
  }
  f = message.getSpSpuContent();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      common_sp_spu_content_pb.SpSpuContent.serializeBinaryToWriter
    );
  }
  f = message.getCategoryList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      common_sp_spu_categories_pb.SpCategoryWp.serializeBinaryToWriter
    );
  }
  f = message.getOptionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option.serializeBinaryToWriter
    );
  }
  f = message.getSkuOptionList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption.serializeBinaryToWriter
    );
  }
};


/**
 * optional proto.SpSpu sp_spu = 1;
 * @return {?proto.proto.SpSpu}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.getSpSpu = function() {
  return /** @type{?proto.proto.SpSpu} */ (
    jspb.Message.getWrapperField(this, common_sp_spu_pb.SpSpu, 1));
};


/**
 * @param {?proto.proto.SpSpu|undefined} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.setSpSpu = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.clearSpSpu = function() {
  return this.setSpSpu(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.hasSpSpu = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional proto.SpSpuContent sp_spu_content = 2;
 * @return {?proto.proto.SpSpuContent}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.getSpSpuContent = function() {
  return /** @type{?proto.proto.SpSpuContent} */ (
    jspb.Message.getWrapperField(this, common_sp_spu_content_pb.SpSpuContent, 2));
};


/**
 * @param {?proto.proto.SpSpuContent|undefined} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.setSpSpuContent = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.clearSpSpuContent = function() {
  return this.setSpSpuContent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.hasSpSpuContent = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated proto.SpCategoryWp category = 3;
 * @return {!Array<!proto.proto.SpCategoryWp>}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.getCategoryList = function() {
  return /** @type{!Array<!proto.proto.SpCategoryWp>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_sp_spu_categories_pb.SpCategoryWp, 3));
};


/**
 * @param {!Array<!proto.proto.SpCategoryWp>} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.setCategoryList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.proto.SpCategoryWp=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.SpCategoryWp}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.addCategory = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.proto.SpCategoryWp, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.clearCategoryList = function() {
  return this.setCategoryList([]);
};


/**
 * repeated Option option = 4;
 * @return {!Array<!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option>}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.getOptionList = function() {
  return /** @type{!Array<!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option, 4));
};


/**
 * @param {!Array<!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option>} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.setOptionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.addOption = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Option, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.clearOptionList = function() {
  return this.setOptionList([]);
};


/**
 * repeated SkuOption sku_option = 5;
 * @return {!Array<!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption>}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.getSkuOptionList = function() {
  return /** @type{!Array<!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption, 5));
};


/**
 * @param {!Array<!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption>} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.setSkuOptionList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.addSkuOption = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuOption, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.prototype.clearSkuOptionList = function() {
  return this.setSkuOptionList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.repeatedFields_ = [3,5,6,7,8,9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.toObject = function(includeInstance, msg) {
  var f, obj = {
    spSku: (f = msg.getSpSku()) && common_sp_sku_pb.SpSku.toObject(includeInstance, f),
    imageList: jspb.Message.toObjectList(msg.getImageList(),
    common_sp_sku_images_pb.SpSkuImages.toObject, includeInstance),
    stockQuantity: jspb.Message.getFieldWithDefault(msg, 4, 0),
    specificationList: jspb.Message.toObjectList(msg.getSpecificationList(),
    common_specifications_pb.SpecificationMessage.toObject, includeInstance),
    addReqList: jspb.Message.toObjectList(msg.getAddReqList(),
    common_additional_requirements_pb.AdditionalReqMessage.toObject, includeInstance),
    priceList: jspb.Message.toObjectList(msg.getPriceList(),
    common_sp_sku_price_pb.SpSkuPriceNew.toObject, includeInstance),
    promotionPriceList: jspb.Message.toObjectList(msg.getPromotionPriceList(),
    common_sp_sku_promotion_price_pb.SpSkuPromotionPrice.toObject, includeInstance),
    spProtocolSkuPriceList: jspb.Message.toObjectList(msg.getSpProtocolSkuPriceList(),
    common_sp_protocol_sku_price_pb.SpProtocolSkuPrice.toObject, includeInstance),
    favorite: jspb.Message.getFieldWithDefault(msg, 10, 0),
    inTransit: jspb.Message.getFieldWithDefault(msg, 11, 0),
    notificationMe: jspb.Message.getFieldWithDefault(msg, 12, 0),
    deliveryDate: jspb.Message.getFieldWithDefault(msg, 13, 0),
    orderedQuantity: jspb.Message.getFieldWithDefault(msg, 14, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp;
  return proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_sp_sku_pb.SpSku;
      reader.readMessage(value,common_sp_sku_pb.SpSku.deserializeBinaryFromReader);
      msg.setSpSku(value);
      break;
    case 3:
      var value = new common_sp_sku_images_pb.SpSkuImages;
      reader.readMessage(value,common_sp_sku_images_pb.SpSkuImages.deserializeBinaryFromReader);
      msg.addImage(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setStockQuantity(value);
      break;
    case 5:
      var value = new common_specifications_pb.SpecificationMessage;
      reader.readMessage(value,common_specifications_pb.SpecificationMessage.deserializeBinaryFromReader);
      msg.addSpecification(value);
      break;
    case 6:
      var value = new common_additional_requirements_pb.AdditionalReqMessage;
      reader.readMessage(value,common_additional_requirements_pb.AdditionalReqMessage.deserializeBinaryFromReader);
      msg.addAddReq(value);
      break;
    case 7:
      var value = new common_sp_sku_price_pb.SpSkuPriceNew;
      reader.readMessage(value,common_sp_sku_price_pb.SpSkuPriceNew.deserializeBinaryFromReader);
      msg.addPrice(value);
      break;
    case 8:
      var value = new common_sp_sku_promotion_price_pb.SpSkuPromotionPrice;
      reader.readMessage(value,common_sp_sku_promotion_price_pb.SpSkuPromotionPrice.deserializeBinaryFromReader);
      msg.addPromotionPrice(value);
      break;
    case 9:
      var value = new common_sp_protocol_sku_price_pb.SpProtocolSkuPrice;
      reader.readMessage(value,common_sp_protocol_sku_price_pb.SpProtocolSkuPrice.deserializeBinaryFromReader);
      msg.addSpProtocolSkuPrice(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFavorite(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setInTransit(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNotificationMe(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setDeliveryDate(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOrderedQuantity(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpSku();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_sp_sku_pb.SpSku.serializeBinaryToWriter
    );
  }
  f = message.getImageList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      common_sp_sku_images_pb.SpSkuImages.serializeBinaryToWriter
    );
  }
  f = message.getStockQuantity();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getSpecificationList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      common_specifications_pb.SpecificationMessage.serializeBinaryToWriter
    );
  }
  f = message.getAddReqList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      common_additional_requirements_pb.AdditionalReqMessage.serializeBinaryToWriter
    );
  }
  f = message.getPriceList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      7,
      f,
      common_sp_sku_price_pb.SpSkuPriceNew.serializeBinaryToWriter
    );
  }
  f = message.getPromotionPriceList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      common_sp_sku_promotion_price_pb.SpSkuPromotionPrice.serializeBinaryToWriter
    );
  }
  f = message.getSpProtocolSkuPriceList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      9,
      f,
      common_sp_protocol_sku_price_pb.SpProtocolSkuPrice.serializeBinaryToWriter
    );
  }
  f = message.getFavorite();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getInTransit();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getNotificationMe();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getDeliveryDate();
  if (f !== 0) {
    writer.writeInt64(
      13,
      f
    );
  }
  f = message.getOrderedQuantity();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
};


/**
 * optional proto.SpSku sp_sku = 1;
 * @return {?proto.proto.SpSku}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.getSpSku = function() {
  return /** @type{?proto.proto.SpSku} */ (
    jspb.Message.getWrapperField(this, common_sp_sku_pb.SpSku, 1));
};


/**
 * @param {?proto.proto.SpSku|undefined} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.setSpSku = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.clearSpSku = function() {
  return this.setSpSku(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.hasSpSku = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated proto.SpSkuImages image = 3;
 * @return {!Array<!proto.proto.SpSkuImages>}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.getImageList = function() {
  return /** @type{!Array<!proto.proto.SpSkuImages>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_sp_sku_images_pb.SpSkuImages, 3));
};


/**
 * @param {!Array<!proto.proto.SpSkuImages>} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.setImageList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.proto.SpSkuImages=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.SpSkuImages}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.addImage = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.proto.SpSkuImages, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.clearImageList = function() {
  return this.setImageList([]);
};


/**
 * optional int32 stock_quantity = 4;
 * @return {number}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.getStockQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.setStockQuantity = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * repeated proto.shop.SpecificationMessage specification = 5;
 * @return {!Array<!proto.proto.shop.SpecificationMessage>}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.getSpecificationList = function() {
  return /** @type{!Array<!proto.proto.shop.SpecificationMessage>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_specifications_pb.SpecificationMessage, 5));
};


/**
 * @param {!Array<!proto.proto.shop.SpecificationMessage>} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.setSpecificationList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.proto.shop.SpecificationMessage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.shop.SpecificationMessage}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.addSpecification = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.proto.shop.SpecificationMessage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.clearSpecificationList = function() {
  return this.setSpecificationList([]);
};


/**
 * repeated proto.shop.AdditionalReqMessage add_req = 6;
 * @return {!Array<!proto.proto.shop.AdditionalReqMessage>}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.getAddReqList = function() {
  return /** @type{!Array<!proto.proto.shop.AdditionalReqMessage>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_additional_requirements_pb.AdditionalReqMessage, 6));
};


/**
 * @param {!Array<!proto.proto.shop.AdditionalReqMessage>} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.setAddReqList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.proto.shop.AdditionalReqMessage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.shop.AdditionalReqMessage}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.addAddReq = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.proto.shop.AdditionalReqMessage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.clearAddReqList = function() {
  return this.setAddReqList([]);
};


/**
 * repeated proto.SpSkuPriceNew price = 7;
 * @return {!Array<!proto.proto.SpSkuPriceNew>}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.getPriceList = function() {
  return /** @type{!Array<!proto.proto.SpSkuPriceNew>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_sp_sku_price_pb.SpSkuPriceNew, 7));
};


/**
 * @param {!Array<!proto.proto.SpSkuPriceNew>} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.setPriceList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 7, value);
};


/**
 * @param {!proto.proto.SpSkuPriceNew=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.SpSkuPriceNew}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.addPrice = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 7, opt_value, proto.proto.SpSkuPriceNew, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.clearPriceList = function() {
  return this.setPriceList([]);
};


/**
 * repeated proto.SpSkuPromotionPrice promotion_price = 8;
 * @return {!Array<!proto.proto.SpSkuPromotionPrice>}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.getPromotionPriceList = function() {
  return /** @type{!Array<!proto.proto.SpSkuPromotionPrice>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_sp_sku_promotion_price_pb.SpSkuPromotionPrice, 8));
};


/**
 * @param {!Array<!proto.proto.SpSkuPromotionPrice>} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.setPromotionPriceList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.proto.SpSkuPromotionPrice=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.SpSkuPromotionPrice}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.addPromotionPrice = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.proto.SpSkuPromotionPrice, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.clearPromotionPriceList = function() {
  return this.setPromotionPriceList([]);
};


/**
 * repeated proto.SpProtocolSkuPrice sp_protocol_sku_price = 9;
 * @return {!Array<!proto.proto.SpProtocolSkuPrice>}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.getSpProtocolSkuPriceList = function() {
  return /** @type{!Array<!proto.proto.SpProtocolSkuPrice>} */ (
    jspb.Message.getRepeatedWrapperField(this, common_sp_protocol_sku_price_pb.SpProtocolSkuPrice, 9));
};


/**
 * @param {!Array<!proto.proto.SpProtocolSkuPrice>} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.setSpProtocolSkuPriceList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 9, value);
};


/**
 * @param {!proto.proto.SpProtocolSkuPrice=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.SpProtocolSkuPrice}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.addSpProtocolSkuPrice = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 9, opt_value, proto.proto.SpProtocolSkuPrice, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.clearSpProtocolSkuPriceList = function() {
  return this.setSpProtocolSkuPriceList([]);
};


/**
 * optional int32 favorite = 10;
 * @return {number}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.getFavorite = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.setFavorite = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 in_transit = 11;
 * @return {number}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.getInTransit = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.setInTransit = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional int32 notification_me = 12;
 * @return {number}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.getNotificationMe = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.setNotificationMe = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional int64 delivery_date = 13;
 * @return {number}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.getDeliveryDate = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.setDeliveryDate = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional int32 ordered_quantity = 14;
 * @return {number}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.getOrderedQuantity = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.prototype.setOrderedQuantity = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.toObject = function(includeInstance, msg) {
  var f, obj = {
    spu: (f = msg.getSpu()) && proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.toObject(includeInstance, f),
    skuList: jspb.Message.toObjectList(msg.getSkuList(),
    proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.toObject, includeInstance),
    deliveryDays: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg;
  return proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp;
      reader.readMessage(value,proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.deserializeBinaryFromReader);
      msg.setSpu(value);
      break;
    case 2:
      var value = new proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp;
      reader.readMessage(value,proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.deserializeBinaryFromReader);
      msg.addSku(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDeliveryDays(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpu();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp.serializeBinaryToWriter
    );
  }
  f = message.getSkuList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp.serializeBinaryToWriter
    );
  }
  f = message.getDeliveryDays();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional SpuWp spu = 1;
 * @return {?proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.prototype.getSpu = function() {
  return /** @type{?proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp} */ (
    jspb.Message.getWrapperField(this, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp, 1));
};


/**
 * @param {?proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SpuWp|undefined} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.prototype.setSpu = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.prototype.clearSpu = function() {
  return this.setSpu(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.prototype.hasSpu = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated SkuWp sku = 2;
 * @return {!Array<!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp>}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.prototype.getSkuList = function() {
  return /** @type{!Array<!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp, 2));
};


/**
 * @param {!Array<!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp>} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg} returns this
*/
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.prototype.setSkuList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.prototype.addSku = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.SkuWp, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.prototype.clearSkuList = function() {
  return this.setSkuList([]);
};


/**
 * optional string delivery_days = 3;
 * @return {string}
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.prototype.getDeliveryDays = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg} returns this
 */
proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes.Msg.prototype.setDeliveryDays = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


goog.object.extend(exports, proto.proto.shop.product.buyer.pullSpuQuickShopDetailRes);
