// source: shop/product/buyer/shopProductPullPageDataRes.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg', null, global);
goog.exportSymbol('proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.displayName = 'proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.repeatedFields_, null);
};
goog.inherits(proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.displayName = 'proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.toObject = function(includeInstance, msg) {
  var f, obj = {
    spuId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    imageLink: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    minPrice: jspb.Message.getFieldWithDefault(msg, 4, ""),
    maxPrice: jspb.Message.getFieldWithDefault(msg, 5, ""),
    originalMaxPrice: jspb.Message.getFieldWithDefault(msg, 6, ""),
    originalMinPrice: jspb.Message.getFieldWithDefault(msg, 7, ""),
    skuUuid: jspb.Message.getFieldWithDefault(msg, 8, ""),
    skuType: jspb.Message.getFieldWithDefault(msg, 9, ""),
    protocolMinPrice: jspb.Message.getFieldWithDefault(msg, 10, ""),
    protocolMaxPrice: jspb.Message.getFieldWithDefault(msg, 11, ""),
    skuCount: jspb.Message.getFieldWithDefault(msg, 12, 0),
    noNextDayDelivery: jspb.Message.getFieldWithDefault(msg, 13, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu;
  return proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSpuId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setImageLink(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMinPrice(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMaxPrice(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginalMaxPrice(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setOriginalMinPrice(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setSkuUuid(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setSkuType(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setProtocolMinPrice(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setProtocolMaxPrice(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSkuCount(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNoNextDayDelivery(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSpuId();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getImageLink();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getMinPrice();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getMaxPrice();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getOriginalMaxPrice();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getOriginalMinPrice();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getSkuUuid();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getSkuType();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getProtocolMinPrice();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getProtocolMaxPrice();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getSkuCount();
  if (f !== 0) {
    writer.writeInt32(
      12,
      f
    );
  }
  f = message.getNoNextDayDelivery();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
};


/**
 * optional int32 spu_id = 1;
 * @return {number}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.getSpuId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} returns this
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.setSpuId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string image_link = 2;
 * @return {string}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.getImageLink = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} returns this
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.setImageLink = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} returns this
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string min_price = 4;
 * @return {string}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.getMinPrice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} returns this
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.setMinPrice = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string max_price = 5;
 * @return {string}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.getMaxPrice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} returns this
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.setMaxPrice = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string original_max_price = 6;
 * @return {string}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.getOriginalMaxPrice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} returns this
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.setOriginalMaxPrice = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string original_min_price = 7;
 * @return {string}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.getOriginalMinPrice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} returns this
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.setOriginalMinPrice = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string sku_uuid = 8;
 * @return {string}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.getSkuUuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} returns this
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.setSkuUuid = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string sku_type = 9;
 * @return {string}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.getSkuType = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} returns this
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.setSkuType = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string protocol_min_price = 10;
 * @return {string}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.getProtocolMinPrice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} returns this
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.setProtocolMinPrice = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string protocol_max_price = 11;
 * @return {string}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.getProtocolMaxPrice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} returns this
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.setProtocolMaxPrice = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional int32 sku_count = 12;
 * @return {number}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.getSkuCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} returns this
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.setSkuCount = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional int32 no_next_day_delivery = 13;
 * @return {number}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.getNoNextDayDelivery = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu} returns this
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.prototype.setNoNextDayDelivery = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.toObject = function(includeInstance, msg) {
  var f, obj = {
    count: jspb.Message.getFieldWithDefault(msg, 2, 0),
    spuList: jspb.Message.toObjectList(msg.getSpuList(),
    proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg;
  return proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCount(value);
      break;
    case 3:
      var value = new proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu;
      reader.readMessage(value,proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.deserializeBinaryFromReader);
      msg.addSpu(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCount();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getSpuList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu.serializeBinaryToWriter
    );
  }
};


/**
 * optional int32 count = 2;
 * @return {number}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg} returns this
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.prototype.setCount = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * repeated Spu spu = 3;
 * @return {!Array<!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu>}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.prototype.getSpuList = function() {
  return /** @type{!Array<!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu, 3));
};


/**
 * @param {!Array<!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu>} value
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg} returns this
*/
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.prototype.setSpuList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu=} opt_value
 * @param {number=} opt_index
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu}
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.prototype.addSpu = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.proto.shop.product.buyer.shopProductPullPageDataRes.Spu, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg} returns this
 */
proto.proto.shop.product.buyer.shopProductPullPageDataRes.Msg.prototype.clearSpuList = function() {
  return this.setSpuList([]);
};


goog.object.extend(exports, proto.proto.shop.product.buyer.shopProductPullPageDataRes);
